var slideimages = new Array() // create new array to preload images
slideimages[0] = new Image() // create new instance of image object
slideimages[0].src = "ugimg/clg1.jpg" // set image src property to image path, preloading image in the process
slideimages[1] = new Image()
slideimages[1].src = "ugimg/clg2.jpg" 
slideimages[2] = new Image()
slideimages[2].src = "ugimg/clg3.jpg" 
slideimages[3] = new Image()
slideimages[3].src = "ugimg/clg4.jpg" 
slideimages[4] = new Image()
slideimages[4].src = "ugimg/clg5.jpg" 
slideimages[5] = new Image()
slideimages[5].src = "ugimg/clg6.jpg" 
slideimages[6] = new Image()
slideimages[6].src = "ugimg/clg7.jpg" 
slideimages[7] = new Image()
slideimages[7].src ="ugimg/clg8.jpg" 
slideimages[8] = new Image()
slideimages[8].src = "ugimg/clg9.jpg" 

