var slideimages = new Array() // create new array to preload images
slideimages[0] = new Image() // create new instance of image object
slideimages[0].src = "pgimg/clg1.jpg" // set image src property to image path, preloading image in the process
slideimages[1] = new Image()
slideimages[1].src = "pgimg/clg2.jpg" 
slideimages[2] = new Image()
slideimages[2].src = "pgimg/clg3.jpg" 
slideimages[3] = new Image()
slideimages[3].src = "pgimg/clg4.jpg" 
slideimages[4] = new Image()
slideimages[4].src = "pgimg/clg5.jpg" 
slideimages[5] = new Image()
slideimages[5].src = "pgimg/clg6.jpg" 
slideimages[6] = new Image()
slideimages[6].src = "pgimg/clg7.jpg" 