var slideimages = new Array() // create new array to preload images
slideimages[0] = new Image() // create new instance of image object
slideimages[0].src = "image/ank1.jpg" // set image src property to image path, preloading image in the process
slideimages[1] = new Image()
slideimages[1].src = "image/ank2.jpg"
slideimages[2] = new Image()
slideimages[2].src = "image/ank2.jpg"
slideimages[3] = new Image()
slideimages[3].src = "image/ank3.jpg"
slideimages[4] = new Image()
slideimages[4].src = "image/ank4.jpg"
slideimages[5] = new Image()
slideimages[5].src = "image/ank5.jpg"
slideimages[6] = new Image()
slideimages[6].src = "image/ank6.jpg"
slideimages[7] = new Image()
slideimages[7].src = "image/ank7.jpg"
slideimages[8] = new Image()
slideimages[8].src = "image/ank8.jpg"
