var slideimages = new Array() // create new array to preload images
slideimages[0] = new Image() // create new instance of image object
slideimages[0].src = "pgimg/shubham.jpg" // set image src property to image path, preloading image in the process
slideimages[1] = new Image()
slideimages[1].src = "pgimg/kumari.jpg"
slideimages[2] = new Image()
slideimages[2].src = "pgimg/aman.jpg"
slideimages[3] = new Image()
slideimages[3].src = "pgimg/vani.jpg"
slideimages[4] = new Image()
slideimages[4].src = "pgimg/bappa.jpg"
slideimages[5] = new Image()
slideimages[5].src = "pgimg/vani.jpg"