var slideimages = new Array() // create new array to preload images
slideimages[0] = new Image() // create new instance of image object
slideimages[0].src = "ugimg/manish.jpg" // set image src property to image path, preloading image in the process
slideimages[1] = new Image()
slideimages[1].src = "ugimg/shashank.jpg"
slideimages[2] = new Image()
slideimages[2].src = "ugimg/shruti.jpg"
slideimages[3] = new Image()
slideimages[3].src = "ugimg/raj.jpg"
slideimages[4] = new Image()
slideimages[4].src = "ugimg/toshi.jpg"
slideimages[5] = new Image()
slideimages[5].src = "ugimg/priyanka.jpg"
